// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0lF25WXa9knFcY-aEGC09n12GeU1TYt8',
    appId: '1:506819980388:web:4fd5ea7b9c1ef6034e4371',
    messagingSenderId: '506819980388',
    projectId: 'mynotes-a7620',
    authDomain: 'mynotes-a7620.firebaseapp.com',
    storageBucket: 'mynotes-a7620.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPSdK0um6TzLsm8xaoKHsBDIkjvBQ6TMg',
    appId: '1:506819980388:android:94d785477969e5044e4371',
    messagingSenderId: '506819980388',
    projectId: 'mynotes-a7620',
    storageBucket: 'mynotes-a7620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXWFjvIfX4-ARvftZ_SIq6e4xM0rFmxqI',
    appId: '1:506819980388:ios:ed26169ae7125f064e4371',
    messagingSenderId: '506819980388',
    projectId: 'mynotes-a7620',
    storageBucket: 'mynotes-a7620.firebasestorage.app',
    iosBundleId: 'com.firstaap.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXWFjvIfX4-ARvftZ_SIq6e4xM0rFmxqI',
    appId: '1:506819980388:ios:ed26169ae7125f064e4371',
    messagingSenderId: '506819980388',
    projectId: 'mynotes-a7620',
    storageBucket: 'mynotes-a7620.firebasestorage.app',
    iosBundleId: 'com.firstaap.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0lF25WXa9knFcY-aEGC09n12GeU1TYt8',
    appId: '1:506819980388:web:fc9dbd55f28396594e4371',
    messagingSenderId: '506819980388',
    projectId: 'mynotes-a7620',
    authDomain: 'mynotes-a7620.firebaseapp.com',
    storageBucket: 'mynotes-a7620.firebasestorage.app',
  );
}
